#
# Secrets
#
---
apiVersion: v1
kind: Secret
metadata:
  name: regkey
  namespace: verificat
data:
  .dockerconfigjson: <REPLACE_WITH_64BASE_OF_FULL_DOCKERCONFIG_JSON>
type: kubernetes.io/dockerconfigjson
