#
# Ingress
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verificat
  namespace: verificat
spec:
  ingressClassName: traefik
  rules:
    - host: verificat.rainbowq.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verificat
                port:
                  number: 4330
