---
# Creates the secret for connecting to AWS SecretsManager
apiVersion: v1
kind: Secret
type: Generic
metadata:
  name: awssm-secret
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    # Without being set, reflection defaults to allowing all namespaces.
    # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "external-secrets,verificat"
    # Without being set, reflection happens to all namespaces.
    # reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "external-secrets,verificat"
data:
  lstack-access-key: LKIAQAAAAAAACVDDECFK
  lstack-secret-access-key: TEtJQVFBQUFBQUFBQ1ZEREVDRksK
  # lstack-access-key: "19Vixqsr4sBX4pqbWbK7aZ2kUMOZZqEQn0z9wj7K"
  # lstack-secret-access-key: "MTlWaXhxc3I0c0JYNHBxYldiSzdhWjJrVU1PWlpxRVFuMHo5d2o3Swo="
