---
# This secret store uses the auth inside
# the AWS Secret awsm-secret for gaining access
# to AWS Secrets Manager for retrieving external secrets.
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: eso-store
  namespace: verificat
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: lstack-access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: lstack-secret-access-key
